FROM node:16-bullseye-slim

WORKDIR /app

COPY package*.json ./
COPY ./bin/server.js ./bin/server.js
COPY ./src/server.js ./src/server.js
COPY ./config/ ./config/

EXPOSE 3001

CMD [ "npm", "run", "server" ]